import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfGenerator {
  static Future<void> generateAndShareValuationReport({
    required String artistName,
    required double estimatedValue,
    required String platform,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Container(
            padding: const pw.EdgeInsets.all(32),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Header(
                  level: 0,
                  child: pw.Text('FluxtonX Valuation Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.teal800)),
                ),
                pw.SizedBox(height: 32),
                pw.Text('Artist: $artistName', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.Text('Platform: ${platform.toUpperCase()}', style: pw.TextStyle(fontSize: 14, color: PdfColors.grey700)),
                pw.SizedBox(height: 24),
                pw.Container(
                  padding: const pw.EdgeInsets.all(16),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.teal50,
                    borderRadius: pw.BorderRadius.circular(8),
                    border: pw.Border.all(color: PdfColors.teal200),
                  ),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Estimated Catalog Valuation', style: pw.TextStyle(fontSize: 14, color: PdfColors.teal900)),
                      pw.SizedBox(height: 8),
                      pw.Text('\$${_formatNumber(estimatedValue)}', style: pw.TextStyle(fontSize: 32, fontWeight: pw.FontWeight.bold, color: PdfColors.teal800)),
                    ],
                  ),
                ),
                pw.SizedBox(height: 48),
                pw.Text('Generated by FluxtonX Catalog Calculator Mobile App.', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
              ],
            ),
          );
        },
      ),
    );

    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: '${artistName.replaceAll(' ', '_')}_valuation.pdf',
    );
  }

  static String _formatNumber(double num) {
    if (num >= 1000000) return '${(num / 1000000).toStringAsFixed(2)}M';
    if (num >= 1000) return '${(num / 1000).toStringAsFixed(1)}K';
    return num.toStringAsFixed(0);
  }
}
